---
- name: Deploy to develop
  hosts: develop-server
  vars:
    server_port: 80
  become: yes

  tasks:
  - name: Ensure python3 is present
    apt:
        name: python3
        state: present
  - name: ensure virtualenv is present
    apt:
        name: virtualenv
        state: present
  - name: Cloning git repo
    git:
        repo: https://github.com/lipflip010/abad.git
        dest: /var/www/abad
        force: yes
        version: prod
        accept_hostkey: yes
  - name: build python projects
    pip:
        requirements: /var/www/abad/requirements.txt
        virtualenv: /var/www/abad/env
        virtualenv_python: python3
  - name: Copy systemd service file to server
    template:
      src: templates/abad.service
      dest: /etc/systemd/system
      owner: root
      group: root
    notify: Start abad

  - name: Start abad
    systemd:
      name: abad
      daemon_reload: yes
      state: restarted
      enabled: yes

