---
- name: "Deploying Updates to {{ server }}-server"
  hosts: "{{ server }}-server"
  become: yes
  tasks:
    - name: Updating Repository
      git:
        repo: https://github.com/lipflip010/abad.git
        dest: /var/www/abad
        force: yes
        version: develop
        accept_hostkey: yes
    - name: Restarting abad
      systemd:
        name: abad
        daemon_reload: yes
        state: restarted
        enabled: yes